# Lily-Cloud/backend/fly.toml
app = "lily-rose-ai"

[build]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.http_options]
    h2_backend = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256